### PR TITLE
Merge experimental branch

### PR DESCRIPTION
**Pull request by argilo**
It's probably not a bad time to merge the experimental branch into master again.

Feedback appreciated @pclov3r @classicjazz @tylert and anyone else.

### CODE REVIEW

**Comment by tylert** [comment]
@argilo the experimental branch (commit 266d94d) builds ok and seems to run well for me.

**Comment by awesie** [comment]
I reviewed the recent merges and tested with a few inputs. It looks like removing the resampler has generally improved BER.

**Comment by pclov3r** [comment]
It seems to be fine.

Didn't do much testing with the removal of the resampler but it appeared to work correctly for me.

**Comment by classicfm** [comment]
I have also noticed that the removal of the resampler seems to improve reception. Just this evening actually. I did some side by side testing, run this version, then run a version prior to the removal. It seems like the resampler-less version does better, in that it does not lose sync or have so many CRC errors, whereas the older version, on the same station, has those problems.

**Comment by argilo** [comment]
@awesie Good idea checking the BER. I just went over my recordings of 14 Las Vegas stations and all have equal or (in most cases) better BER with the resampler removed. I guess that's to be expected since the resampler will inevitably introduce some distortion.

**Comment by argilo** [comment]
It seems everyone's happy with the changes, so I'll merge to master.

**Comment by classicjazz** [comment]
This new master build has much improved reception. I am not seeing either the log errors or hearing the audible chirps/dropouts in my limited testing.

**Pull request merged**
