### PR TITLE
Implement long station name & station location.

### PR DESCRIPTION
**Pull request by argilo**
This builds on #57 and gets further towards implementing #38. Here I've implemented SIS message types 2 (long station name) and 4 (station location).

Some stations put useful information in these fields, but others leave them set to default, placeholder values.

@itdaniher

### CODE REVIEW

**Comment by itdaniher** [comment]
03:39:22 DEBUG pids.c:132: Station Name: WKLB-FM
03:39:22 DEBUG pids.c:115: Country: US, FCC facility ID: 10542
03:39:22 DEBUG pids.c:174: Station location: 42.310547, -184.763794, 32m

Hmm.... -184 is not a valid longitude, as far as I can tell.

**Comment by itdaniher** [comment]
From http://data.fcc.gov/download/license-view/fcc-license-view-data-csv-format.zip, the valid coordinates are:

42,18,27.0,"N",71,13,27.0,"W"

Looks like the Lat is correct, not sure why Lon is messed up.

Delighted to see this much working though, thanks for looping me in!

**Comment by argilo** [comment]
I'd added type 5 (station message) as well.

**Comment by argilo** [comment]
> Looks like the Lat is correct, not sure why Lon is messed up.

I've seen all sorts of messed up SIS messages in the stations I've looked at. For instance, one station has a long name of "Univ Slgn" and another is broadcasting a station message of "This is a big long message from the station." And about half have their coordinates set to 99.214600, -244.031372, 128m.

**Comment by argilo** [comment]
Station slogan is now included as well.

**Pull request merged**
