### PR TITLE
Fix distortion with parametric stereo and re-enable parametric stereo

### PR DESCRIPTION
**Pull request by logiconcepts819**
The proposed commit fixes the audio distortion problem with parametric stereo streams reported by #260 and also re-enables parametric stereo for HDC.  It also updates faad2 to the latest version.

Feel free to let me know if you see any additional changes in the DRM parametric stereo decoder that could be needed.

### CODE REVIEW

**Comment by TheDaChicken** [comment]
Yep, I definitely can say that this fixed the issue!

**Comment by pclov3r** [comment]
@argilo 

This has been here awhile. Is this good enough to merge? 

Would like to see this fixed :)

**Comment by argilo** [comment]
I was hoping @awesie might comment, since he knows a lot more about the codec than I do. But since it's been a while, I'll have a peek at this soon and get it merged.

**Comment by awesie** [comment]
Looking at the code quickly, it seems reasonable enough. If it fixes the audio distortions, then I would say go for it. I would have to do a lot more digging to check its accuracy.

**Comment by TheDaChicken** [comment]
Well, we have no clue if it fixed the issue for other people as it did with me... I assume it did.

Ah, I wish HDRadio didn't sound crap on the subchannels....

**Comment by argilo** [comment]
I had a look over the faad2 changes, and they seems reasonable to me. I also tested with the I/Q recording from https://github.com/theori-io/nrsc5/issues/260#issuecomment-1020848180, and the audio sounds reasonable. Merging.

**Pull request merged**
