### PR TITLE
Speed up adjust_data and remove fast_cexpf.

### PR DESCRIPTION
**Pull request by argilo**
This change builds on top of #106 and gives another significant speedup simply by moving the expensive complex exponentiations out of the innermost loop of `adjust_data`.

The speedup is around 12% on Intel, and on my Raspberry Pi 3 the CPU utilization is reduced to around 50%.

Since complex exponentiations are no longer a bottleneck, I removed `fast_cexpf`.

### CODE REVIEW

**Comment by argilo** [comment]
Bit error rates are the same before & after this change, so I expect it's correct.

**Comment by pclov3r** [comment]
Looks like this PR is removing the unsafe math optimizations?

If so perhaps that should be removed from the readme as well.

**Comment by argilo** [comment]
@pclov3r I haven't completely removed `USE_FAST_MATH` yet; it still reduces the size of the FIR filter. I'll remove that in a future PR.

**Comment by awesie** [comment]
This looks good to me. Feel free to merge with #106 once it is ready.

**Pull request merged**
