### PR TITLE
Refactor into a library and use SoapySDR.

### LINKED ISSUE #122: Other SDR support
Now this is probably a huge feature request that is complicated but I like to see some other SDR support such as the Airspy, SDRPlay, Etc.

### PR DESCRIPTION
**Pull request by awesie**
Major change to provide a public API that is used by the
example command line application.

Fix #122 by using SoapySDR instead of librtlsdr.

### CODE REVIEW

**Comment by awesie** [comment]
@pclov3r Can you test if this branch works with SDRplay?

**Comment by pclov3r** [comment]
@awesie I'll give it a try now here in a bit and see.

**Comment by pclov3r** [comment]
Having some major issues using it with a RTL-SDR

It seems the autogain doesn't work correctly and the MER is all over the place.

**Comment by pclov3r** [comment]
Log of the unstable MER bouncing all over the place. 

`linux; GNU C++ version 6.3.0 20170221; Boost_106200; UHD_003.009.005-0-unknown

Detached kernel driver
Found Rafael Micro R820T tuner
Reattached kernel driver
Detached kernel driver
Found Rafael Micro R820T tuner
04:42:54 INFO  nrsc5.c:183: Driver: RTLSDR
04:42:54 INFO  nrsc5.c:184: Hardware: RTLSDR
Exact sample rate is: 1488375.071248 Hz
[R82XX] PLL not locked!
04:42:55 DEBUG nrsc5.c:201: Sample rate: 1488375.00
04:42:55 DEBUG nrsc5.c:202: Bandwidth: 0.00
04:42:55 DEBUG nrsc5.c:203: Decimation: 2
[R82XX] PLL not locked!
[INFO] Using format CS16.
04:42:55 DEBUG sync.c:243: Block @ 25
04:42:56 INFO  sync.c:220: Synchronized!
04:42:56 DEBUG pids.c:136: Station Name: KWAV-FM
04:42:56 DEBUG pids.c:119: Country: US, FCC facility ID: 21
04:42:56 DEBUG pids.c:270: Audio program 0: public, type 0, sound experience 0
04:42:56 DEBUG pids.c:270: Audio program 1: public, type 0, sound experience 0
04:42:57 DEBUG pids.c:187: Station location: 36.584961, -134.146118, 48m
04:42:57 DEBUG pids.c:328: Local time zone offset: -480 minutes, DST sched. 1, local DST? yes, regional DST? yes
04:42:57 INFO  main.c:232: MER: 14.3 dB (lower), 14.8 dB (upper)
04:42:58 INFO  main.c:219: BER: 0.000000, avg: 0.000000, min: 0.000000, max: 0.000000
04:42:58 INFO  main.c:266: Title: Just Dance
04:42:58 INFO  main.c:268: Artist: Lady Gaga
04:42:58 INFO  main.c:276: XHDR: 0 00000000 0
04:42:58 DEBUG frame.c:514: ignoring partial pdu
04:42:58 DEBUG frame.c:514: ignoring partial pdu
04:42:58 DEBUG pids.c:317: Pending leap second offset: 0, current leap second offset: 0
04:42:59 INFO  main.c:232: MER: 14.5 dB (lower), 15.0 dB (upper)
04:42:59 INFO  main.c:219: BER: 0.000000, avg: 0.000000, min: 0.000000, max: 0.000000
04:42:59 INFO  main.c:266: Title: Just Dance
04:42:59 INFO  main.c:268: Artist: Lady Gaga
04:42:59 INFO  main.c:276: XHDR: 0 00000000 0
04:42:59 INFO  main.c:266: Title: Just Dance
04:42:59 INFO  main.c:268: Artist: Lady Gaga
04:42:59 INFO  main.c:276: XHDR: 0 00000000 0
04:42:59 DEBUG main.c:247: Audio bit rate: 47.3 kbps
04:43:00 INFO  main.c:232: MER: -5.2 dB (lower), -8.7 dB (upper)
04:43:01 INFO  main.c:219: BER: 0.235617, avg: 0.078539, min: 0.000000, max: 0.235617
04:43:01 DEBUG sync.c:199: lost sync (29, 29)!
04:43:01 DEBUG sync.c:243: Block @ 29
04:43:01 DEBUG sync.c:243: Block @ 0
04:43:02 INFO  sync.c:220: Synchronized!
04:43:02 DEBUG pids.c:136: Station Name: KWAV-FM
04:43:02 DEBUG pids.c:119: Country: US, FCC facility ID: 21
04:43:03 INFO  main.c:232: MER: -13.1 dB (lower), -10.1 dB (upper)
04:43:03 INFO  main.c:219: BER: 0.184115, avg: 0.104933, min: 0.000000, max: 0.235617
04:43:04 DEBUG sync.c:199: lost sync (-1, -1)!
04:43:04 DEBUG sync.c:243: Block @ 31
04:43:05 DEBUG sync.c:243: Block @ 0
04:43:05 INFO  sync.c:220: Synchronized!
04:43:05 DEBUG pids.c:136: Station Name: KWAV-FM
04:43:05 DEBUG pids.c:119: Country: US, FCC facility ID: 21
04:43:05 DEBUG pids.c:270: Audio program 0: public, type 0, sound experience 0
04:43:05 DEBUG pids.c:270: Audio program 1: public, type 0, sound experience 0
04:43:05 DEBUG pids.c:187: Station location: 36.584961, -134.146118, 48m
04:43:06 INFO  main.c:232: MER: 13.8 dB (lower), 15.0 dB (upper)
04:43:06 INFO  main.c:219: BER: 0.000982, avg: 0.084143, min: 0.000000, max: 0.235617
04:43:06 INFO  frame.c:308: psd crc mismatch
04:43:06 INFO  main.c:266: Title: Just Dance
04:43:06 INFO  main.c:268: Artist: Lady Gaga
04:43:06 INFO  main.c:276: XHDR: 0 00000000 0
04:43:06 DEBUG main.c:247: Audio bit rate: 46.3 kbps
04:43:07 DEBUG main.c:247: Audio bit rate: 46.8 kbps
04:43:07 ERROR output.c:49: Decode error: PNS not allowed in DRM data stream
O04:43:08 INFO  main.c:232: MER: -14.4 dB (lower), -12.7 dB (upper)
04:43:08 INFO  main.c:219: BER: 0.178650, avg: 0.099894, min: 0.000000, max: 0.235617
04:43:08 DEBUG sync.c:199: lost sync (-1, -1)!
04:43:09 DEBUG sync.c:243: Block @ 30
^C
`

**Comment by pclov3r** [comment]
And to answer your question it appears that my SDRplay is detected and it attempts to work but zero sync.

**Comment by awesie** [comment]
@pclov3r Thank you. Could you test with the latest changes on awesie/experimental?

I realized that I broke the halfband filter, which should be why the rtlsdr behavior was wonky.

For the SDRplay, I hardcoded a value for the sample rate. It is unfortunate that there will need to be a table of supported devices with the supported sample rate, but hopefully it will make things reliable.

**Comment by pclov3r** [comment]
The rtl-sdr is still being wonky here with bouncing MER.

**Comment by pclov3r** [comment]
@awesie you make any progress with this at all?

**Comment by awesie** [comment]
I've been implementing some remaining features. I haven't personally encountered issues with rtlsdr or hackrf. I will probably go ahead merge everything into the experimental branch soon.

Did you have a chance to test the sdrplay with the latest version?

**Comment by pclov3r** [comment]
@awesie Hum... Perhaps something specific here.

I'll try and get to testing sometime later today.

**Comment by pclov3r** [comment]
Alright I think i traced my bouncing MER down to a buffer or latency issue. If i do a wave file output it appears to be fine without issues.

Will test the SDR play here in a bit.

**Comment by awesie** [comment]
Thanks for testing. I suspected that could be the issue and added some additional audio buffers in b7f6250b7565c0241b49e0fb1c4b19e94b9d99fe.

**Comment by pclov3r** [comment]
Okay so having some issues with my SDRplay. To be more specific i have a SDRplay RSP2 which has multiple antenna ports so that could be the issue.

**Comment by billybobgot** [comment]
That could be due to the sdrplay using a 12-bit ADC

**Comment by pclov3r** [comment]
@awesie so this has been sitting now for over 11 month without anything new.

As you said previously there is some major concerns using this as it does add yet another dependency and increases complexity a bit. 

At this point perhaps this PR should be closed? 

If not I'd like to see SDRplay be a optional feature and not mandatory at this point so we can continue the way it's been before. 

Thanks!

**Comment by argilo** [comment]
I like the idea of turning nrsc5 into a library, since it should make life easier for projects that want to build on top of it (like https://github.com/cmnybo/nrsc5-gui and https://github.com/KYDronePilot/hdfm). I'm less enthusiastic about pulling in SoapySDR as a dependency since it doesn't immediately open the door to supporting that many additional SDRs. Additional resampling code is needed to handle their various sample rates, especially for models that have a fixed sample rate.

**Comment by pclov3r** [comment]
@argilo That actually sounds like a good idea.

**Comment by davide125** [comment]
Yeah making this into a library as a first step would be great. Additional backends like soapysdr could be useful but IMO it'll be easier to do as a separate/orthogonal change.

**Comment by awesie** [comment]
If I find some time, I'll split this PR in two: transition to a library and transition to SoapySDR.

**Comment by pclov3r** [comment]
@awesie Would they be separate branches or be left as configurable options?

**Comment by awesie** [comment]
Closing in lieu of #147.

**Pull request closed without merging**
