### PR TITLE
Merge experimental branch.

### PR DESCRIPTION
**Pull request by argilo**
Since the last merge, there have been some significant performance and sensitivity improvements, as well as a bug fix. It's probably worth merging to master, as long as things are working well. So far things look good.

Feedback appreciated @pclov3r @classicjazz @classicfm @tylert.

### CODE REVIEW

**Comment by pclov3r** [comment]
The experimental branch seems to work great here.

**Comment by pclov3r** [comment]
Just to add even with a weak channel that looks like this I still have good RX performance with minimal CRC errors. 

```
19:16:48 INFO  sync.c:337: MER: 6.6 dB (lower), 5.7 dB (upper)
19:16:48 INFO  decode.c:77: BER: 0.016793, avg: 0.016666, min: 0.013857, max: 0.035771
```

**Comment by awesie** [comment]
I think this is safe, though my testing is still limited to the sample files I have on my computer.

One regression is this weak signal: http://server1.awesie.org/1071.36.4. It has better performance before 4b73a859b717260321662e9d3ee67ea4b678b136. On the other hand, 4b73a859b717260321662e9d3ee67ea4b678b136 improves performance for http://server1.awesie.org/samples955.

If no one experiences real issues with experimental within the next day, I'd say merge it into master.

**Comment by argilo** [comment]
Thanks for those samples, @awesie. I've added them to my test suite, as well as bunch of other recordings I made. Overall 4b73a859b717260321662e9d3ee67ea4b678b136 seems to have a neutral effect on BER but I'm curious why there are a couple recordings where BER is noticeably worse afterwards. There could be a bug somewhere else in the frequency tracking.

For now, it seems fine to leave that commit in.

**Comment by classicfm** [comment]
This is a definite improvement. BER has dropped across the board, sometimes dramatically, even with strong stations. For WWHT-FM, a 50 kW class B at 10.7 miles (and a HAAT of 152 meters, which is only middling for this area), on experimental's current HEAD, a BER average of 0.000730 after about a minute. On the previous commit I was using (ac77c51), BER average of 0.015680.

**Comment by classicjazz** [comment]
Comparing the before and after of the experimental build:

**WHYY**
* Still can't lock in. It just sits at "11:22:49 INFO  main.c:61: Gain: 49.6 dB, CNR: 2.996687 dB"

**WRTI**
* Before: 11:15:54 INFO  sync.c:315: MER: 4.3 dB (lower), 7.1 dB (upper)
* After: 11:17:40 INFO  sync.c:337: MER: 7.4 dB (lower), 7.8 dB (upper)-----------------]
11:17:40 INFO  decode.c:77: BER: 0.007884, avg: 0.007975, min: 0.007024, max: 0.009017

**WXPN**
* Before: 11:16:08 INFO  sync.c:315: MER: 9.0 dB (lower), 10.1 dB (upper)
11:16:08 INFO  decode.c:77: BER: 0.001193, avg: 0.001235, min: 0.001193, max: 0.
* After:11:18:16 INFO  sync.c:337: MER: 9.8 dB (lower), 10.7 dB (upper)----------------]
11:18:16 INFO  decode.c:77: BER: 0.000588, avg: 0.001132, min: 0.000588, max: 0.

**Comment by argilo** [comment]
Thanks for testing, everyone! I'll merge for now, and look into @awesie's weak signal issue soon.

**Comment by classicfm** [comment]
In case anyone cares, I finally heard back from my classical radio station. They are currently operating on back up equipment due to a lightning strike. They are broadcasting in HD, but at a drastically reduced level. The analog signal is apparently not as affected by this. They have to build and install a new antenna, which is going to take a while. They do not know when it'll all be done, it's just "moving forward".

I finally broke down and ordered a TXCO radio from RTL-SDR.com. Knowing what I know now I have my doubts it'll let me receive their HD transmission before the repairs are completed, but we'll see, I guess.

**Pull request merged**
