### PR TITLE
Prototype a Python CLI app.

### PR DESCRIPTION
**Pull request by argilo**
It might be useful to merge in my prototype Python CLI app at this point. it's already helping to test the API, and it can be executed as part of Travis CI so help us catch bugs earlier. (For instance in `nrsc5_open_pipe` and `nrsc5_pipe_samples`, which are not used by the C CLI app.)

### CODE REVIEW

**Comment by argilo** [comment]
Heres the result of the CI run: https://travis-ci.org/argilo/nrsc5/builds/488195677

**Comment by pclov3r** [comment]
Is there something i'm missing here? When attempting to use this i get ImportError: No module named 'pyaudio' however it's installed.

Any pointers?

**Comment by pclov3r** [comment]
My fault scratch that. Needed to install the python3 version of pyaudio.

**Comment by argilo** [comment]
In case it's useful to you, I got stuck trying to compile it and used the binary available from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio

**Comment by argilo** [comment]
By the way, here's what the Python CLI can do so far:

* take input from RTL-SDR, file, or stdin
* play audio packets on the sound card

And that's about it! It currently ignores all the other events produced by libnrsc5.

It might be nice to split it into two pieces: a Python wrapper for libnrsc5, and the CLI. Other apps could reuse the Python wrapper and make their own UI.

**Pull request merged**
